version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: jamae
      POSTGRES_PASSWORD: jamae
      POSTGRES_DB: jamae_project
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./apps/web
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://jamae:jamae@db:5432/jamae_project?schema=public
      NEXTAUTH_URL: http://localhost:3000
    env_file:
      - ./apps/web/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - web_storage:/app/storage

volumes:
  db_data:
  web_storage:
